project:
  type: website
  output-dir: docs

website:
  title: "R Cheats"
  repo-url: https://github.com/edgar-treischl/daf
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    include-in-header: 
      - progress-bar.html
    toc: true



